export const data = [
  "It is certain",
  "Reply hazy, Try again",
  "It is decidedly so",
  "Ask again later",
  "Without a doubt",
  "Better not tell you now",
  "Yes definitly",
  "Cannot predict now",
  "You may rely on it",
  "Concentrate and ask again",
  "As I see it, yes",
  "Don't count on it",
  "Most likely",
  "My reply is no",
  "Outlook good",
  "My sources say no",
  "Yes",
  "Outlook not so good",
  "Signs point to yes",
  "Very doubtful",
];
